/*
     * By installing or using this file, you are confirming on behalf of the entity
     * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
     * the SugarCRM Inc. Master Subscription Agreement ("MSA"), which is viewable at:
     * http://www.sugarcrm.com/master-subscription-agreement
     *
     * If Company is not bound by the MSA, then by installing or using this file
     * you are agreeing unconditionally that Company will be bound by the MSA and
     * certifying that you have authority to bind Company accordingly.
     *
     * Copyright  2004-2013 SugarCRM Inc.  All rights reserved.
     */
({fieldTag:'input[type=file]',showNoData:false,events:{"click .delete":"delete","change input[type=file]":"selectImage"},plugins:['File','FieldDuplicate'],initialize:function(options){app.view.Field.prototype.initialize.call(this,options);if(!this.model.hasImageRequiredValidator){this.model.hasImageRequiredValidator=true;this.model.addValidationTask('image_required',_.bind(this._doValidateImageField,this));}},_dispose:function(){this.model.hasImageRequiredValidator=false;this.model._validationTasks=_.omit(this.model._validationTasks,'image_required');app.view.Field.prototype._dispose.call(this);},onFieldDuplicate:function(){if(this.disposed||this.view.name!=='merge-duplicates'){return;}
this.render();},_render:function(){this.model.fileField=this.name;app.view.Field.prototype._render.call(this);if(this.view&&this.view.meta&&this.view.meta.type==='list'){this.width=this.height=this.$el.parent().height()||42;this.def.width=this.def.height=undefined;}else{this.width=parseInt(this.def.width||this.def.height,10)||50;this.height=parseInt(this.def.height,10)||this.width;}
this.resizeWidth(this.width);this.resizeHeight(this.height);this.$('.image_field').removeClass('hide');this.$('img').addClass('hide').on('load',$.proxy(this.resizeWidget,this));return this;},format:function(value){if(value){value=this.buildUrl()+"&_hash="+value;}
return value;},bindDataChange:function(){var viewType=this.view.name||this.options.viewName;var ignoreViewType=["edit","create","create-actions"];if(_.indexOf(ignoreViewType,viewType)<0&&this.view.action!=="edit"){app.view.Field.prototype.bindDataChange.call(this);}},bindDomChange:function(){this.$(this.fieldTag).on('focus',_.bind(this.handleFocus,this));},selectImage:function(e){var self=this,$input=self.$('input[type=file]');self.preview=true;self.clearErrorDecoration();self.model.uploadFile(self.name,$input,{field:self.name,success:function(rsp){var fileId=(rsp[self.name])?rsp[self.name]['guid']:null;var url=app.api.buildFileURL({module:self.module,id:'temp',field:self.name,fileId:fileId});var image=$('<img>').addClass('hide').attr('src',url).on('load',$.proxy(self.resizeWidget,self));self.$('.image_preview').html(image);self.model.trigger("change","image");},error:function(error){var fieldError={},errors={};fieldError[error.responseText]={};errors[self.name]=fieldError;self.model.trigger('error:validation:'+this.field,fieldError);self.model.trigger('error:validation',errors);}},{temp:true});},'delete':function(e){var self=this;if(this.preview===true){self.preview=false;self.clearErrorDecoration();self.render();}else{var confirmMessage=app.lang.get('LBL_IMAGE_DELETE_CONFIRM',self.module);if(confirm(confirmMessage)){app.api.call('delete',self.buildUrl({htmlJsonFormat:false}),{},{success:function(){self.model.unset(self.name);self.model.set(self.name,null);if(!self.disposed)self.render();},error:function(data){app.error.handleHttpError(data,{});}});}}},buildUrl:function(options){return app.api.buildFileURL({module:this.module,id:this._duplicateBeanId?this._duplicateBeanId:this.model.id,field:this.name},options);},resizeWidget:function(){var image=this.$('.image_preview img, .image_detail img');if(!image[0])return;var isDefHeight=!_.isUndefined(this.def.height)&&this.def.height>0,isDefWidth=!_.isUndefined(this.def.width)&&this.def.width>0;if(isDefWidth){image.css('width',this.width);}
if(isDefHeight){image.css('height',this.height);}
if(!isDefHeight&&!isDefWidth)
image.css({'height':this.height,'width':this.width});this.resizeHeight(image.height());if(isDefHeight&&!isDefWidth){var newWidth=Math.floor((this.height / image[0].naturalHeight)*image[0].naturalWidth);image.css('width',newWidth);this.resizeWidth(newWidth);}
image.removeClass('hide');this.$('.delete').remove();var icon=this.preview===true?'remove':'trash';image.closest('label, a').after('<span class="image_btn delete icon-'+icon+' " />');},formatPX:function(size){size=parseInt(size,10);return size+'px';},resizeHeight:function(height){var $image_field=this.$('.image_field'),isEditAndIcon=this.$('.icon-plus').length>0;if(isEditAndIcon){var $image_btn=$image_field.find('.image_btn');var edit_btn_height=parseInt($image_btn.css('height'),10);var previewHeight=parseInt(height,10);previewHeight-=edit_btn_height?edit_btn_height:0;previewHeight=this.formatPX(previewHeight);$image_field.find('.icon-plus').css({lineHeight:previewHeight});}
var totalHeight=this.formatPX(height);$image_field.css({'height':totalHeight,minHeight:totalHeight,lineHeight:totalHeight});$image_field.find('label').css({lineHeight:totalHeight});},resizeWidth:function(width){var $image_field=this.$('.image_field'),width=this.formatPX(width),isInHeaderpane=$(this.el).closest('.headerpane').length>0,isInRowFluid=$(this.el).closest('.row-fluid').closest('.record').length>0;if(isInHeaderpane||!isInRowFluid){$image_field.css({'width':width});}else{$image_field.css({'maxWidth':width});}},_doValidateImageField:function(fields,errors,callback){var $input=this.$('input[type=file]');if(this.def.required&&(_.isEmpty($input)||_.isEmpty($input.val()))){errors[this.name]=errors[this.name]||{};errors[this.name].required=true;}
callback(null,fields,errors);},handleValidationError:function(errors){var errorMessages=[];if(this.action==='detail'){this.setMode('edit');}
this.$('.image_preview').html('<i class="icon-remove"></i>');this.$('label').after('<span class="image_btn delete icon-remove" />');this.$el.closest('.record-cell').addClass("error");this.$el.addClass('input-append error');_.each(errors,function(errorContext,errorName){errorMessages.push(app.error.getErrorString(errorName,errorContext));});this.$('.image_field').append(this.exclamationMarkTemplate(errorMessages));this.createErrorTooltips(this.$('.error-tooltip'));},clearErrorDecoration:function(){this.$('.delete').remove();this.$('.error-tooltip').remove();this.$el.closest('.record-cell').removeClass('error');this.$el.removeClass('input-append error');}})